In [22]:
#preperation
import torch
from torch.utils.data import Dataset
torch.manual_seed(1)

#simple Dataset
class toy_set(Dataset):
  def __init__(self, length=100, transform= None):
    self.len=length
    self.x = 2 * torch.ones(length,2)
    self.y = torch.ones(length,1)
    self.transform=transform

  def __getitem__(self,id):
    result = self.x[id],self.y[id]
    if(self.transform):
      result = self.transform(result)
    return result
  
  def __len__(self):
    return self.len

data_set = toy_set(length=300)
print('Simple Dataset with length of',data_set.len)
for i in range(0,4):
  print(data_set[i])


#transform
class addxmulty(object):
  def __init__(self,addx=10,multy=2):
    self.addx = addx
    self.multy = multy

  def __call__(self,sample):
    x = self.addx + sample[0]
    y = self.multy * sample[1]
    sample = x,y
    return sample

my_transform =addxmulty(addx=100,multy=4)
data_set = toy_set(length=234, transform=my_transform)
print('\nTransform Dataset with length of',data_set.len)
for i in range(0,4):
  print(data_set[i])



#COMPOSE
from torchvision import transforms

class addconstant(object):
  def __init__(self, add=100):
    self.add = add
  
  def __call__(self, result):
    x = self.add + result[0]
    y = self.add + result[1]
    result = x,y
    return result


my_transform2 = addconstant(534)
composed_transform = transforms.Compose([my_transform,my_transform2])

data_set = toy_set(length=145, transform= composed_transform)
print('\nComposed Transform Dataset with length of',data_set.len)
for i in range(0,4):
  print(data_set[i])


Simple Dataset with length of 300
(tensor([2., 2.]), tensor([1.]))
(tensor([2., 2.]), tensor([1.]))
(tensor([2., 2.]), tensor([1.]))
(tensor([2., 2.]), tensor([1.]))

Transform Dataset with length of 234
(tensor([102., 102.]), tensor([4.]))
(tensor([102., 102.]), tensor([4.]))
(tensor([102., 102.]), tensor([4.]))
(tensor([102., 102.]), tensor([4.]))

Composed Transform Dataset with length of 145
(tensor([636., 636.]), tensor([538.]))
(tensor([636., 636.]), tensor([538.]))
(tensor([636., 636.]), tensor([538.]))
(tensor([636., 636.]), tensor([538.]))
