In [13]:
import torch
import torch.nn as nn
import matplotlib.pyplot as plt
torch.manual_seed(1)

model1 = nn.Sequential(nn.Linear(2,1),nn.Sigmoid())
X = torch.tensor([[-1.0,3.0],[3.0,6.0],[3.0,1.0]])
yhat = model1(X)
print(list(model.parameters()))
print(yhat)


class Log_Regr(nn.Module):
  def __init__(self,in_):
    super(Log_Regr, self).__init__()
    self.linear=nn.Linear(in_,1)

  def forward(self,x):
    yhat = torch.sigmoid(self.linear(x))
    return yhat

model = Log_Regr(2)
print(list(model.parameters()))
yhat = model(X)
print(yhat)

[Parameter containing:
tensor([[ 0.3319, -0.6657]], requires_grad=True), Parameter containing:
tensor([0.4241], requires_grad=True)]
tensor([[0.1919],
        [0.2856],
        [0.6556]], grad_fn=<SigmoidBackward>)
[Parameter containing:
tensor([[ 0.3319, -0.6657]], requires_grad=True), Parameter containing:
tensor([0.4241], requires_grad=True)]
tensor([[0.1296],
        [0.0708],
        [0.6801]], grad_fn=<SigmoidBackward>)
